### ISSUE TITLE
Gradle Issue

### ISSUE THREAD

**Issue by iagocanalejas** [MuhammadArsalanChishti/Cuboid-Circle-Button#2]
Hi men. This error is happening in last android studio version.

``` ruby
Error:Could not find com.android.support.constraint:constraint-layout:1.0.0-alpha1.
Required by:
    Picshopping:app:unspecified > com.cuboid:cuboidcirclebutton:1.0.3
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

**Comment by ColinWa** [comment]
This might help:
http://stackoverflow.com/a/39934917/2414129

**Comment by adeelahmad94** [comment]
`'com.android.support.constraint:constraint-layout:1.0.0-beta5'
` worked for me. but had to manually import and update the dependency inside module.
