### ISSUE TITLE
Module dependency is too old

### ISSUE THREAD

**Issue by adeelahmad94** [MuhammadArsalanChishti/Cuboid-Circle-Button#3]
The dependency '`com.android.support.constraint:constraint-layout:1.0.0-alpha1`' is obsolete and gradle wont sync anything below alpha2 while beta5 is available till this day. I spent hectic 30 mins figuring it out and finally had to import the module and manually update the dependency to : 

`'com.android.support.constraint:constraint-layout:1.0.0-beta5'`

Better push an update with latest dependency so that gradle syncing would be possible.

**Comment by marcespinoza** [comment]
yes, same problem. not found other solution

**Comment by MuhammadArsalanChishti** [comment]
will update soon

**Comment by MuhammadArsalanChishti** [comment]
updated
