### ISSUE TITLE
Change button color programmatically at runtime

### ISSUE THREAD

**Issue by ColinWa** [MuhammadArsalanChishti/Cuboid-Circle-Button#4]
i have tried to change button color programmatically as follows:
`cuboidButton.setCircle_color(getResources().getColor(R.color.colorAccent));`

but no effect of button

**Comment by NiDaAppDev** [comment]
having the same issue, I would like to get some help with it (:

**Comment by osmer** [comment]
Any update on this?

**Comment by NiDaAppDev** [comment]
Nope. At least not for me ):
I got an advice that worked fine for me - use a custom circle button, a button with circle button that also has the functionality of this circle button

**Comment by osmer** [comment]
@TempND could you provide us some examples??

**Comment by NiDaAppDev** [comment]
Yes, of course, I thought I already did it, sorry
Read this thread :
https://stackoverflow.com/questions/9884202/custom-circle-button

**Comment by pellyadolfo** [comment]
does not work
