### ISSUE TITLE
Align Icon in center

### ISSUE THREAD

**Issue by nicks258** [MuhammadArsalanChishti/Cuboid-Circle-Button#5]
How to align icon in button in center? by default it comes in left side. My code 
`<com.cuboid.cuboidcirclebutton.CuboidButton
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:layout_centerInParent="true"
        android:textColor="@android:color/white"
        app:cub_border_color="@color/color_4062BB"
        app:cub_border_radius="2dp"
        app:cub_color="@color/color_59C3C3"
        app:cub_fontstyle="fonts/Bellerose.ttf"
        app:cub_hover_color="@color/colorAccent2"
        app:cub_icon="@drawable/gallery"
        app:cub_riple_effect="true"
        />`

**Comment by Butz85** [comment]
android:layout_centerInParent="true"  <-- doesn't work for me.

**Comment by MuhammadArsalanChishti** [comment]
by default icon is in center i tried above code and its is correct 
note: please test in real device
